---
apiVersion: batch/v1
kind: Job
metadata:
  name: signatures.sigprobs
  namespace: tool-signatures
  labels:
    name: signatures.sigprobs
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  template:
    metadata:
      labels:
        name: signatures.sigprobs
        toolforge: tool
    spec:
      containers:
        - name: sigprobs
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/signatures/signatures/venv/bin/python3", "/data/project/signatures/signatures/src/sigprobs.py"]
          args: ["$(SP_SITE)"]
          workingDir: /data/project/signatures
          env:
            - name: HOME
              value: /data/project/signatures
          imagePullPolicy: Always
      restartPolicy: Never
